import { useState } from "react";
import Head from "next/head";
import SideBar from "../components/sidebar";
import Header from "../components/Header";
import MainSection from "../components/MainSection";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       
      <main className="flex ">
        <div className="w-1/4  h-screen p-3 flex flex-col align-middle fixed">
          <SideBar />
        </div>
        <div className=" w-3/4  p-3 border-l-2 border-[#F1F6FC] absolute right-0">
          <Header />
          <MainSection />
        </div>
      </main>
    </div>
  );
}
